{
 "title": "Dashboard rcp220",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latence moyenne",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=~\"/predict|/feedback\"}[1m]) / rate(http_request_duration_seconds_count{handler=~\"/predict|/feedback\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=~\"/predict|/feedback\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreurs 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilité API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"api_radio\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}